### ISSUE TITLE
HTTP Error: 502, "Bad gateway", "/graphql"

### ISSUE THREAD

**Issue by vapniks** [magit/forge#20]
When I `forge-pull` my repo from github I get this error:

```
error in process filter: HTTP Error: 502, "Bad gateway", "/graphql", ((data . "null") (errors ((message . "Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `C1F2:0E37:3E93014:8BF14F7:5C1B8B27` when reporting this issue."))))
```

The magit buffer doesn't appear to update initially, but if I kill the buffer and restart it the pull requests and issues are listed.

**Comment by tarsius** [comment]
Off topic: Due to how `markdown-mode` works it is necessary to put empty lines before and after a code block or the surrounding paragraphs won't get justified.  (I have modified your post accordingly.)

@jrblevin Is that something that could be changed in `markdown-mode` (or maybe just `gfm-mode`)?

**Comment by tarsius** [comment]
> 502, "Bad gateway"

If I remember correctly, I got the same uninformative error message during development.

The problem is that the GraphQL API does not support notifications and the REST API does not provide all the required information.  So Forge makes a REST request to get the list of notifications and then builds an GraphQL request from the response to fetch details about the referenced issue, pull-requests and repositories.  For a while I did make a separate request for each topic, but that was to slow and not asynchronous.

The current implementation uses GraphQL "aliases".  The problem with that is that there is no pagination, which increases the odds of timeouts.  I though I have already addressed that by "paginating" at the client side and making multiple GraphQL requests, but it turns out that I have only implemented that in a similar context in `emir` (the package used to maintain the Emacsmirror).

I'll have to do something similar here.

**Comment by tarsius** [comment]
By default and for the time being `forge-pull` does not fetch notifications anymore.  See the new `forge-pull-notifications` option.

**Comment by vapniks** [comment]
Thankyou, I'll try to remember the tip about spacing in `markdown-mode` when I start using emacs for creating issues (this one was created on the webpage where spacing doesn't appear to make any difference to the display).

**Comment by vapniks** [comment]
Btw, I get the same HTTP error when I try `M-x forge-pull-notifications`. In this case I do not see any change or new buffers appear, and when I do `M-x forge-list-notifications` I get an empty `forge-notifications` buffer.
Should it display all notifications, or just participating ones (which I don't have atm)?

**Comment by vermiculus** [comment]
When I do `F Y` (which is `M-x forge-pull-notifications`), I do get a list of notifications bucketed by repository.

Given that I'm not participating in the majority of conversations in magit or forge (but I still see those notifications), I would assume that I'm getting non-participating notifications as well.

**Comment by tarsius** [comment]
`forge--pull-notifications` now fetches details about at most 100 topics at once now.  This should normally be small enough to prevent a timeout.  If it is not, then tweak the (for now) hardcoded limit.

Please also let me know how many notifications are being fetched in your case by multiplying the total in `Pulling notifications (page 1/1)...` by 100.  For me it is <=100 and I expect that that is the normal case.

**Comment by tarsius** [comment]
I'll consider this fixed until I hear otherwise.

**Comment by nicklan** [comment]
I'm still getting this error on a fairly large repo.  I can pull notifications, and that works okay, but trying to do `F-y` results in:
```
Pulling REPO...
error in process filter: ghub--signal-error: HTTP Error: 502, "Bad gateway", "/graphql", ((data . "null") (errors ((message . "Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `CC2C:4FEA:A1771C1:CBF40CE:5C33F7E5` when reporting this issue."))))
error in process filter: HTTP Error: 502, "Bad gateway", "/graphql", ((data . "null") (errors ((message . "Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `CC2C:4FEA:A1771C1:CBF40CE:5C33F7E5` when reporting this issue."))))
```

Unlike above however, even if I restart the magit buffer there are no pull requests or issues listed.

I can open a new issue if you like, and let me know if there's more debug info that could help.

Thanks!

**Comment by timor** [comment]
Trying to `forge-pull` NixOS/nixpkgs repeatedly fails for me.  Usually with this error (immediately), but one of them was also a 403 (see #69).

I then tried using a prefix argument of "2019-01-01" (Is that the correct syntax, anyway?), hoping it will somehow reduce the number/volume of requests.  The command ran for much longer (progress indicator in the mode line counted pages to beyond 13), but in the end again failed with a 403.

Is there some way to debug which/how many requests to the API are made when executing `forge-pull`?

**Comment by yashi** [comment]
maybe related to https://github.com/magit/ghub/issues/83

**Comment by tarsius** [comment]
Thanks!

**Comment by c3d** [comment]
Hi @tarsius, I don't know if you want to reopen, but I have this very consistently with https://github.com/kata-containers/kata-containers, on a variety of machines. I am not sure if you can do anything on your side, though, but that's a test case you can look at if you have any interest.

**Comment by c3d** [comment]
@tarsius Still seeing the problem on the `kata-containers` repo, if you want to give it a try (with `N f f`. Fetching notifications only seems to work.

Is there an option that would allow me to split the requests into smaller chunks, maybe that could help?

**Comment by pymander** [comment]
This error happens always with the `kubernetes/kubernetes` repo, which has over 100,000 topics to pull. Might be a great one for testing.

**Comment by hh** [comment]
@pymander I'm also having issues working with `kubernetes/kubernetes` and `kubernetes/k8s.io`. I'll try and take a look over the next few months.

**Comment by tarsius** [comment]
I've added a new variable `forge.graphqlItemLimit`, which you can set using `n t l` and which should help. I've set it to 50 in Magit's own repository and no longer get any 502s.

**Comment by c3d** [comment]
> I've added a new variable `forge.graphqlItemLimit`, which you can set using `n t l` and which should help. I've set it to 50 in Magit's own repository and no longer get any 502s.

This seems to be working for me as well. Thanks!
