### ISSUE TITLE
forge-pull: (wrong-type-argument (or eieio-object cl-structure-object oclosure) nil)

### ISSUE THREAD

**Issue by hrehfeld** [magit/forge#553]
From a repo status buffer in magit `v3.3.0-599-gf59df798` I press `f n` and then get this error:

```
Debugger entered--Lisp error: (wrong-type-argument (or eieio-object cl-structure-object oclosure) nil)
  #<subr eieio-oref>(nil selective-p)
  eieio-oref--closql-oref(#<subr eieio-oref> nil selective-p)
  apply(eieio-oref--closql-oref #<subr eieio-oref> (nil selective-p))
  eieio-oref(nil selective-p)
  forge-pull(nil nil t)
  funcall-interactively(forge-pull nil nil t)
  call-interactively(forge-pull nil nil)
  command-execute(forge-pull)
```
forge is at 4dfbc3a0ca80101c7a3763df518485bd8106805f , eieio-version "1.4"

might be related to #550

**Comment by tarsius** [comment]
I cannot tell from the backtrace whether this is caused by `code-review`, but because that package is broken until its maintainer makes changes that are necessary due to backward-incompatible changes in `closql`, you should temporarily remove it anyway. See https://github.com/wandersoncferreira/code-review/issues/245 and https://github.com/magit/closql/issues/8.

There also was another, potentially related, issue in EmacSQL, which I fixed a few minutes ago: https://github.com/magit/forge/issues/552. (Usually it takes a few hours for a new package to become available in Melpa, so you might want to wait a bit before trying to update).

**Comment by hrehfeld** [comment]
(I'm not using `code-review`)

Error persists with emacsql="3.1.1.50-git"
